version: '3.1'

services:

    db:
      container_name: database
      image: postgres
      restart: always
      ports:
        - 5432:5432
      env_file:
        - ".env"
  #    network_mode: "host"
  
    adminer:
      container_name: adminer
      image: adminer
      restart: always
      ports:
        - 8080:8080
  #    network_mode: "host"
    
    server:
      container_name: server
      image: server
      command: python server.py
      ports:
        - 3000:3000
  
    tgbot:
      container_name: bot
      build:
        context: .
      command: python app.py
      restart: always
      network_mode: "host"
  
      env_file:
        - ".env"
      depends_on:
        - server